spring.application.name=spring-boot
spring.datasource.url=jdbc:h2:file:./data/vulndb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sr
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.security.user.name=sri
spring.security.user.password=pwd

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE